AgileKernelBundle\Model\ObjectHistory:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        action:
            type: string
            length: 255
        field:
            type: string
            length: 255
            nullable: true

