AgileKernelBundle\Model\ObjectReference:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        objectClass:
            type: text
        objectId:
            type: integer

